export { default as About } from './About/About'
export { Footer } from './Footer/Footer'
export { default as Header } from './Header/Header'
export { Skills } from './Skills/Skills'
export { Testimonials } from './Testimonials/Testimonials'
export { Work } from './Work/Work'